### PR TITLE
React Set up:

### PR DESCRIPTION
**Pull request by sneeu-leeu**
## In milestone 1, I:
- Set up linters and Config files on dev
- Set up react to run in browser

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

- [ ] Please move your actual project from the math-magician folder to the main project directory. 
Capture

 Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by sneeu-leeu** [comment]
Thanks for the review @arslanbisharat,

Could you please tell me exactly what you mean by removing the actual project from the file.
The Files was generated by  running $ npx create-react-app my-app, should all content be removed into the main directory?

Thank you!

**Comment by arslanbisharat** [comment]
> Thanks for the review @arslanbisharat,
> 
> Could you please tell me exactly what you mean by removing the actual project from the file.
> The Files was generated by  running $ npx create-react-app my-app, should all content be removed into the main directory?
> 
> Thank you!

When using npm command to create a project within a folder keep in mind we don't use npx create-react-app my-app, instead we use npx create-react-app . ,
You should have math-magican content generated by next command directly in the repo not in a folder.

**Comment by sneeu-leeu** [comment]
Awesome! 
Thanks for the tip @arslanbisharat

**Review by arslanbisharat — APPROVED** [review]
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashbaord. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Pull request merged**
